name: CI Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test  

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Login to Docker Hub
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      # Build Docker image
      - name: Build the Docker image
        run: docker build -t yassirrachad/pharmaback:latest .

      # Push Docker image to Docker Hub
      - name: Push to Docker Hub
        run: docker push yassirrachad/pharmaback:latest
